# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/events/user-signedup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.events import base_pb2 as protobuf_dot_events_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protobuf/events/user-signedup.proto\x12\x0fprotobuf.events\x1a\x1aprotobuf/events/base.proto\"J\n\x0cUserSignedUp\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12)\n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x18.protobuf.events.Channelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.events.user_signedup_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERSIGNEDUP']._serialized_start=84
  _globals['_USERSIGNEDUP']._serialized_end=158
# @@protoc_insertion_point(module_scope)
