# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/user-signedup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from events import base_pb2 as events_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65vents/user-signedup.proto\x12\x06\x65vents\x1a\x11\x65vents/base.proto\"A\n\x0cUserSignedUp\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12 \n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x0f.events.Channelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.user_signedup_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERSIGNEDUP']._serialized_start=57
  _globals['_USERSIGNEDUP']._serialized_end=122
# @@protoc_insertion_point(module_scope)
